version: '2'
services:
  php:
    image: eszleles:18
#    command: yii migrate --interactive=0 #uncomment for migration, then comment out again
    ports:
      - '8968:80'
    networks:
      - my-new-network
  eszlelesdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: asdasd
      POSTGRES_USER: keltom
      POSTGRES_DB: eszlelesdb
    networks:
      - my-new-network
networks:
  my-new-network:
    driver: bridge
