version: '2'
services:
  php:
    image: eszleles:latest
    ports:
      - '8968:80'
    networks:
      - my-new-network
  eszleles-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: asdasd
      POSTGRES_USER: keltom
      POSTGRES_DB: eszleles
    networks:
      - my-new-network
networks:
  my-new-network:
    driver: bridge
